from . import crm_lead
from . import portfolio_account_level
from . import portfolio_account_level_line
from . import portfolio_bcg_matrix
from . import portfolio_contact_type
from . import portfolio_contact_type_line
from . import portfolio_entry_state
from . import portfolio_entry_type
from . import portfolio_entry_type_line
from . import portfolio_goal_task
from . import portfolio_goal_task_stage
from . import portfolio_goal_task_tag
from . import portfolio_partner_level
from . import portfolio_partner_level_line
from . import portfolio_portfolio
from . import portfolio_reference
from . import portfolio_reference_channel
from . import portfolio_reference_stage
from . import portfolio_reference_tag
from . import portfolio_service_type
from . import portfolio_stage
from . import portfolio_tag
from . import portfolio_target_group
from . import portfolio_technology
from . import portfolio_website_tag
from . import res_partner
from . import res_partner_category
