# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
{
    "name": "Portfolio",
    "summary": """
        Manage portfolio for tender applications.
    """,
    "author": "Mint System GmbH",
    "website": "https://www.mint-system.ch/",
    "category": "Repository",
    "development_status": "Production/Stable",
    "version": "19.0.1.0.0",
    "license": "AGPL-3",
    "depends": ["crm", "mail", "product", "contacts", "knowledge"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/portfolio_account_level.xml",
        "views/portfolio_account_level_line.xml",
        "views/portfolio_bcg_matrix.xml",
        "views/portfolio_contact_type.xml",
        "views/portfolio_contact_type_line.xml",
        "views/portfolio_entry_state.xml",
        "views/portfolio_entry_type.xml",
        "views/portfolio_entry_type_line.xml",
        "views/portfolio_goal_task.xml",
        "views/portfolio_goal_task_stage.xml",
        "views/portfolio_goal_task_tag.xml",
        "views/portfolio_partner_level.xml",
        "views/portfolio_partner_level_line.xml",
        "views/portfolio_portfolio.xml",
        "views/portfolio_reference.xml",
        "views/portfolio_reference_channel.xml",
        "views/portfolio_reference_stage.xml",
        "views/portfolio_reference_tag.xml",
        "views/portfolio_service_type.xml",
        "views/portfolio_stage.xml",
        "views/portfolio_tag.xml",
        "views/portfolio_target_group.xml",
        "views/portfolio_technology.xml",
        "views/portfolio_website_tag.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "images": ["images/screen.png"],
    "demo": ["demo/demo.xml"],
}
